{
  "formatVersion": "1.1",
  "component": {
    "url": "../../int-serializers/1.0/int-serializers-1.0.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "int-serializers",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers-jvm-1.0.jar",
          "url": "int-serializers-jvm-1.0.jar",
          "size": 12057,
          "sha512": "97788003b04448c56717fd7932e5684384eb889c480ff179d666189034fe5e358e758db31338ff13d52717161718f87ae1e4b6da917340d869bfa6aeafa86ae9",
          "sha256": "67153e02cf79cebb8e3e2331ca0ed6aec37a3abf69be837ca38ebc87e6654941",
          "sha1": "500bbaff986c6ff760b84f15fb2c167db12ccd61",
          "md5": "c1b94309b6f635e8c0f81d7ac04e9537"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers-jvm-1.0.jar",
          "url": "int-serializers-jvm-1.0.jar",
          "size": 12057,
          "sha512": "97788003b04448c56717fd7932e5684384eb889c480ff179d666189034fe5e358e758db31338ff13d52717161718f87ae1e4b6da917340d869bfa6aeafa86ae9",
          "sha256": "67153e02cf79cebb8e3e2331ca0ed6aec37a3abf69be837ca38ebc87e6654941",
          "sha1": "500bbaff986c6ff760b84f15fb2c167db12ccd61",
          "md5": "c1b94309b6f635e8c0f81d7ac04e9537"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "int-serializers-jvm-1.0-sources.jar",
          "url": "int-serializers-jvm-1.0-sources.jar",
          "size": 4196,
          "sha512": "91633c3a7ac0fc4716168b064b4ee27396fd6b75be1f34b73781dedb3bb5e1ff8dc9d6a41b69b609d12eb7450b9c896e5b9363774ce45f5e30ebd75532198596",
          "sha256": "97ea4689ae0cbd710d59dacf91b11601179369dff7e7fe309a3389f79a968914",
          "sha1": "39441f27e396bd87f7798b97e6610b633b578a8c",
          "md5": "e295a51bbdaadb8f09215dc74e57cad3"
        }
      ]
    }
  ]
}
