{
  "formatVersion": "1.1",
  "component": {
    "url": "../../int-serializers/1.0/int-serializers-1.0.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "int-serializers",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers.klib",
          "url": "int-serializers-macosarm64-1.0.klib",
          "size": 61805,
          "sha512": "9ca93f075317e7678af48cf3c1aeddd006956f88289f381f9c5d9cb819ce16cf6b0be822276f05b25c8d4a95e63b70d378b058ad0734cfa71c8e6e9a7c93b1fa",
          "sha256": "46562f32feabc8334fe4ac01d6864d2b331164468946953d9a3e056402378947",
          "sha1": "a93771f32f3f3db2a2955fd6f9a1f07e4cdb2f14",
          "md5": "92dfe3e0c33eb71cbb52f7d6fb157985"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "int-serializers-macosarm64-1.0-sources.jar",
          "url": "int-serializers-macosarm64-1.0-sources.jar",
          "size": 4196,
          "sha512": "91633c3a7ac0fc4716168b064b4ee27396fd6b75be1f34b73781dedb3bb5e1ff8dc9d6a41b69b609d12eb7450b9c896e5b9363774ce45f5e30ebd75532198596",
          "sha256": "97ea4689ae0cbd710d59dacf91b11601179369dff7e7fe309a3389f79a968914",
          "sha1": "39441f27e396bd87f7798b97e6610b633b578a8c",
          "md5": "e295a51bbdaadb8f09215dc74e57cad3"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers-macosarm64-1.0-metadata.jar",
          "url": "int-serializers-macosarm64-1.0-metadata.jar",
          "size": 261,
          "sha512": "7c40ce79a5369ba43f9e2fa3601df4d76d3d0933a1a9463a01d50d0b4425fe225b2531e42cbb6146e126e770013efa71f5e661074e80f6b4cea9d54a6f16284c",
          "sha256": "be3389c2dfbb5cccd4ff1a392aadd95ed753f96db6e76efd988d6d1be80ce029",
          "sha1": "dfee9c9f3a4cd39ef691ab910e8c5c461d4f91b1",
          "md5": "cac4252609f06a1b248acfd4b2ae0218"
        }
      ]
    }
  ]
}
