{
  "formatVersion": "1.1",
  "component": {
    "url": "../../int-serializers/1.0/int-serializers-1.0.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "int-serializers",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers.klib",
          "url": "int-serializers-watchosarm32-1.0.klib",
          "size": 61823,
          "sha512": "91169fe57e5ff33115c5b68dd8482b42add2be545a081d0638ba70528a5a57bdaea25be194eca4acfa3178640cd501941f74ad710d8a6642aa0372144f21056b",
          "sha256": "bb7a1c8591053a61f90dc65cde63263554ac9db3bd30a4ec7c06914129ef1bd0",
          "sha1": "4e6cf3d3d41cb3fdea16687df0f66e36fca57b36",
          "md5": "a0127d073a88d11a82bd1d0348dab497"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "int-serializers-watchosarm32-1.0-sources.jar",
          "url": "int-serializers-watchosarm32-1.0-sources.jar",
          "size": 4196,
          "sha512": "91633c3a7ac0fc4716168b064b4ee27396fd6b75be1f34b73781dedb3bb5e1ff8dc9d6a41b69b609d12eb7450b9c896e5b9363774ce45f5e30ebd75532198596",
          "sha256": "97ea4689ae0cbd710d59dacf91b11601179369dff7e7fe309a3389f79a968914",
          "sha1": "39441f27e396bd87f7798b97e6610b633b578a8c",
          "md5": "e295a51bbdaadb8f09215dc74e57cad3"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers-watchosarm32-1.0-metadata.jar",
          "url": "int-serializers-watchosarm32-1.0-metadata.jar",
          "size": 261,
          "sha512": "0f47b30788ad2ed12e98079e0e9fdb0cca852215dc537cc8e60e520def2a398fcaac16faed8e3bd433c44c96f0c23dcccdb36c7238d5bddb692f23d6873728b7",
          "sha256": "7fcf12019b3eea3c1e3b93ee5d10e4e1553f82e90a53dd1907cb098ea651a2e7",
          "sha1": "ac494f85dc3e125a570b1d641177365f6e9d057b",
          "md5": "155a12d37417b30b1e3208f0c978d471"
        }
      ]
    }
  ]
}
