{
  "formatVersion": "1.1",
  "component": {
    "url": "../../int-serializers/1.0/int-serializers-1.0.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "int-serializers",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers.klib",
          "url": "int-serializers-iossimulatorarm64-1.0.klib",
          "size": 61875,
          "sha512": "ea81b17dda6e74601ec867c40792f62e2557ef3632c8ac7b33dc7578bcb9ebf2edc354c4c46868462b8bb62ecf5c064475611a5790b4384a4f462b8f2965bb9b",
          "sha256": "717095e6f38f1bd9576b860483a9758bfc2dd9798d8904e58ca6adbce9e90215",
          "sha1": "939fad52f52413667e99e6c1f36139cc4d4429e7",
          "md5": "e3c91af6fc9cae6313429d433f989d92"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "int-serializers-iossimulatorarm64-1.0-sources.jar",
          "url": "int-serializers-iossimulatorarm64-1.0-sources.jar",
          "size": 4196,
          "sha512": "91633c3a7ac0fc4716168b064b4ee27396fd6b75be1f34b73781dedb3bb5e1ff8dc9d6a41b69b609d12eb7450b9c896e5b9363774ce45f5e30ebd75532198596",
          "sha256": "97ea4689ae0cbd710d59dacf91b11601179369dff7e7fe309a3389f79a968914",
          "sha1": "39441f27e396bd87f7798b97e6610b633b578a8c",
          "md5": "e295a51bbdaadb8f09215dc74e57cad3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers-iossimulatorarm64-1.0-metadata.jar",
          "url": "int-serializers-iossimulatorarm64-1.0-metadata.jar",
          "size": 261,
          "sha512": "75281553b7d2065d1cdf4ffdf3910da44bf659ff3c2c9f14436cec33127ddc958d39295e07fc55b5e3fcc038fec2d2d1e92b8f0077a491df3e792ca96b49ffe3",
          "sha256": "203aa101035777c8af599b448a5143fb6ab019c69cbed6ed5b29fd3dbc22edb1",
          "sha1": "0b0c681fe473cecd89c075ad480b6eacf37fc5f3",
          "md5": "ee02f0dd8da5a8f8c1bffb283a3b55cb"
        }
      ]
    }
  ]
}
