{
  "formatVersion": "1.1",
  "component": {
    "url": "../../int-serializers/1.0/int-serializers-1.0.module",
    "group": "ru.landgrafhomyak.utility",
    "module": "int-serializers",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers.klib",
          "url": "int-serializers-watchosx64-1.0.klib",
          "size": 61807,
          "sha512": "1714672cd3538cfbe5987beafa782a9c5016ba82a44ad9f18959079bc2d466b59420773cec362c2ccedc04ef29698b8cc85b98f2525227e29dde81434f3a65e1",
          "sha256": "3cb83fb99dc17daace132d1c1e990e419aecae72b72141e86d08132c49f58467",
          "sha1": "d8e1d805d463254f4f87f73ed5a5bd4fa43b33c0",
          "md5": "1157d2ec4cce8d8e8338fda55a73f6f4"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "int-serializers-watchosx64-1.0-sources.jar",
          "url": "int-serializers-watchosx64-1.0-sources.jar",
          "size": 4196,
          "sha512": "91633c3a7ac0fc4716168b064b4ee27396fd6b75be1f34b73781dedb3bb5e1ff8dc9d6a41b69b609d12eb7450b9c896e5b9363774ce45f5e30ebd75532198596",
          "sha256": "97ea4689ae0cbd710d59dacf91b11601179369dff7e7fe309a3389f79a968914",
          "sha1": "39441f27e396bd87f7798b97e6610b633b578a8c",
          "md5": "e295a51bbdaadb8f09215dc74e57cad3"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "int-serializers-watchosx64-1.0-metadata.jar",
          "url": "int-serializers-watchosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "a6be48a3f56aab66634cd7927d8b4acb10914fdd954c698e4ee7aa7f6aabf3cff2ee4beac9a4d4d54656399895d5e5138f0cb4f51e254bb4d7962058bab12110",
          "sha256": "eccd1593deaf48e28d0e9bfbb16c295951447ae27b9ff63749913bea1af6ae9a",
          "sha1": "f9c439d83ebee055245ffa36c4efb2741b05be25",
          "md5": "d340557b0e54f965d9974245057b4bd5"
        }
      ]
    }
  ]
}
